name: Terraform Docker + Kube
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v1.1.0
      env:
        PROJECT_ID: royal-282917
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: cluster-1
        ZONE_NAME: us-central1-c
      with:
        args: apply -f ./.github/workflows/k8s
