name: commands

on: [push]

jobs:
    run_commands:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2.0
            - name: Check out code
              
            - name: Publish Docker Action
              uses: jerray/publish-docker-action@v1.0.5
              with:
                # Username used to login docker registry
                username: ${{ secrets.DOCKER_USERNAME }}
                # Password used to login docker registry
                password: ${{ secrets.DOCKER_PASSWORD }}
